# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5ba49061f7ba6c5272084972943622c67856d790df02eadd3be89aaa7f366b5784b4465d11fbf8b8714b50a636be3c4fffd8ce02bcdab62a5915ddad0e2b9543

test:
  secret_key_base: 7a9db5b2e8703616858c0d2c7e2c6795d540d35e4bee35f6bf937806c5345b632b528c7ea30f8f45fb375102c6438fc6c9819859844d01b84447920dd8e22642

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
